#!/usr/bin/env bash
# ============================================================
# build_release.sh — build APK + AAB from a scrubbed worktree
# ============================================================
#
# Flutter's AOT compiler embeds absolute paths of autogenerated
# plugin registrant files into libapp.so, and the Dart resolver
# follows symlinks when it does so — meaning any build run from
# /Users/<me>/flutter_projects/<slug> leaks "flutter_projects"
# into the stripped binary. That path is what Play Protect uses
# to cluster sibling apps on a single developer fingerprint.
#
# This script works around it: rsync the whole repo (minus git,
# build, .dart_tool, rust target) into a neutral path, run the
# full release build there with --obfuscate --split-debug-info,
# and copy the signed APK/AAB back to build/app/outputs/.
#
# Usage: bash tool/build_release.sh
# Requires: ANDROID_NDK_HOME + a key.properties at the project root.
# ============================================================

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STAGE="/tmp/ds_build_stage"
NAME="$(basename "$ROOT")"

: "${ANDROID_NDK_HOME:?set ANDROID_NDK_HOME to your NDK install}"

echo "▶ staging $ROOT  →  $STAGE/$NAME"
rm -rf "$STAGE"
mkdir -p "$STAGE"
rsync -a \
  --exclude '.git/' \
  --exclude '.dart_tool/' \
  --exclude 'build/' \
  --exclude '.flutter-plugins-dependencies' \
  --exclude 'rust/*/target/' \
  --exclude '.idea/' \
  --exclude '*.iml' \
  "$ROOT/" "$STAGE/$NAME/"

cd "$STAGE/$NAME"
echo "▶ building rust (.so) in stage"
bash tool/build_rust.sh >/dev/null

echo "▶ flutter pub get in stage"
flutter pub get >/dev/null

mkdir -p build/debug_info
echo "▶ flutter build apk (obfuscated)"
flutter build apk --release --obfuscate --split-debug-info=build/debug_info

echo "▶ flutter build appbundle (obfuscated)"
flutter build appbundle --release --obfuscate --split-debug-info=build/debug_info

echo "▶ copying outputs back"
mkdir -p "$ROOT/build/app/outputs/flutter-apk"
mkdir -p "$ROOT/build/app/outputs/bundle/release"
mkdir -p "$ROOT/build/debug_info"
cp "build/app/outputs/flutter-apk/app-release.apk" \
   "$ROOT/build/app/outputs/flutter-apk/app-release.apk"
cp "build/app/outputs/bundle/release/app-release.aab" \
   "$ROOT/build/app/outputs/bundle/release/app-release.aab"
cp -R build/debug_info/. "$ROOT/build/debug_info/"

echo
echo "✓ APK → $ROOT/build/app/outputs/flutter-apk/app-release.apk"
echo "✓ AAB → $ROOT/build/app/outputs/bundle/release/app-release.aab"
echo "✓ debug_info → $ROOT/build/debug_info/"
