//! Build-time packer for sealed strings.
//!
//! Reads `sealed/seed.toml`, encrypts every entry with a per-slot keystream
//! derived from a compile-time pepper, and emits `src/sealed_data.rs`
//! containing only `[u8; N]` byte arrays. The plaintext of any sealed value
//! never leaves this script, so `strings libgate_core.so` returns nothing
//! useful for the attacker.
//!
//! Keystream: Chacha-ish mix of (`PEPPER`, slot index, byte offset). Not
//! cryptographically strong — the goal is *obfuscation*, not confidentiality,
//! so even if the pepper leaks the attacker still has to execute the code
//! path that triggers the matching slot.

use serde::Deserialize;
use std::env;
use std::fs;
use std::path::PathBuf;

#[derive(Deserialize, Debug, Default)]
struct Seed {
    endpoint_config: Option<String>,
    user_agent_template: Option<String>,
    js_bootstrap: Option<String>,
    js_telemetry_hook: Option<String>,
    js_frame_cleanup: Option<String>,
    appsflyer_dev_key: Option<String>,
    firebase_topic: Option<String>,
    bundle_id: Option<String>,
    fallback_target: Option<String>,
    relay_secret: Option<String>,
    envelope_schema_field: Option<String>,
    envelope_nonce_field: Option<String>,
    envelope_payload_field: Option<String>,
    envelope_tag_field: Option<String>,
    envelope_schema_rev: Option<String>,
    privacy_url: Option<String>,
    support_url: Option<String>,
}

// Slot IDs are the public contract between Rust and Dart. Keep in lockstep
// with `lib/gate/sealed_ids.dart`.
const SLOT_ORDER: &[&str] = &[
    "endpoint_config",       // 0
    "user_agent_template",   // 1
    "js_bootstrap",          // 2
    "js_telemetry_hook",     // 3
    "js_frame_cleanup",      // 4
    "appsflyer_dev_key",     // 5
    "firebase_topic",        // 6
    "bundle_id",               // 7
    "fallback_target",         // 8
    "relay_secret",            // 9
    "envelope_schema_field",   // 10
    "envelope_nonce_field",    // 11
    "envelope_payload_field",  // 12
    "envelope_tag_field",      // 13
    "envelope_schema_rev",     // 14
    "privacy_url",             // 15
    "support_url",             // 16
];

fn pepper() -> [u8; 32] {
    // Random 32-byte constant. Pre-mixed with slot/offset at runtime.
    [
        0xa3, 0x7b, 0x12, 0xf4, 0x81, 0x29, 0xd6, 0x55,
        0x6e, 0x0d, 0xcf, 0x97, 0x44, 0x3a, 0xe2, 0x1b,
        0x58, 0xbe, 0x74, 0x20, 0xaa, 0x11, 0x9c, 0x63,
        0x8f, 0x37, 0xee, 0x4d, 0x2c, 0xc8, 0x5f, 0x06,
    ]
}

fn stream_byte(slot: u8, i: usize) -> u8 {
    // sip-like mixing of pepper, slot index and byte offset.
    let p = pepper();
    let mut acc = p[(i as usize) & 31] as u32;
    acc ^= (slot as u32).wrapping_mul(0x9E3779B1);
    acc = acc.wrapping_add((i as u32).wrapping_mul(0xB7E15163));
    acc ^= acc.rotate_left(13);
    acc = acc.wrapping_mul(0x5BD1E995);
    acc ^= acc >> 15;
    (acc & 0xff) as u8
}

fn seal(slot: u8, plain: &str) -> Vec<u8> {
    plain
        .as_bytes()
        .iter()
        .enumerate()
        .map(|(i, b)| b ^ stream_byte(slot, i))
        .collect()
}

fn fmt_slice(bytes: &[u8]) -> String {
    let mut out = String::new();
    out.push_str("&[");
    for (i, b) in bytes.iter().enumerate() {
        if i % 12 == 0 {
            out.push_str("\n        ");
        }
        out.push_str(&format!("0x{b:02x}, "));
    }
    out.push_str("\n    ]");
    out
}

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let seed_path = manifest.join("sealed").join("seed.toml");
    println!("cargo:rerun-if-changed=sealed/seed.toml");
    println!("cargo:rerun-if-changed=build.rs");

    let seed: Seed = if seed_path.exists() {
        let raw = fs::read_to_string(&seed_path)
            .expect("read sealed/seed.toml");
        toml::from_str(&raw).expect("parse sealed/seed.toml")
    } else {
        println!("cargo:warning=sealed/seed.toml not found — all slots will be empty");
        Seed::default()
    };

    let mut body = String::new();
    body.push_str("// AUTO-GENERATED by build.rs. DO NOT EDIT.\n");
    body.push_str("// Each slot is XOR-encrypted at build time; see seal.rs for\n");
    body.push_str("// the decryption pass.\n\n");
    body.push_str("pub const SLOT_COUNT: usize = ");
    body.push_str(&SLOT_ORDER.len().to_string());
    body.push_str(";\n\n");

    for (idx, key) in SLOT_ORDER.iter().enumerate() {
        let plain: &str = match *key {
            "endpoint_config" => seed.endpoint_config.as_deref().unwrap_or(""),
            "user_agent_template" => seed.user_agent_template.as_deref().unwrap_or(""),
            "js_bootstrap" => seed.js_bootstrap.as_deref().unwrap_or(""),
            "js_telemetry_hook" => seed.js_telemetry_hook.as_deref().unwrap_or(""),
            "js_frame_cleanup" => seed.js_frame_cleanup.as_deref().unwrap_or(""),
            "appsflyer_dev_key" => seed.appsflyer_dev_key.as_deref().unwrap_or(""),
            "firebase_topic" => seed.firebase_topic.as_deref().unwrap_or(""),
            "bundle_id" => seed.bundle_id.as_deref().unwrap_or(""),
            "fallback_target" => seed.fallback_target.as_deref().unwrap_or(""),
            "relay_secret" => seed.relay_secret.as_deref().unwrap_or(""),
            "envelope_schema_field" => seed.envelope_schema_field.as_deref().unwrap_or(""),
            "envelope_nonce_field" => seed.envelope_nonce_field.as_deref().unwrap_or(""),
            "envelope_payload_field" => seed.envelope_payload_field.as_deref().unwrap_or(""),
            "envelope_tag_field" => seed.envelope_tag_field.as_deref().unwrap_or(""),
            "envelope_schema_rev" => seed.envelope_schema_rev.as_deref().unwrap_or(""),
            "privacy_url" => seed.privacy_url.as_deref().unwrap_or(""),
            "support_url" => seed.support_url.as_deref().unwrap_or(""),
            _ => "",
        };
        let sealed = seal(idx as u8, plain);
        body.push_str(&format!(
            "/// Slot {idx} = {key}\n\
             pub const SLOT_{idx}: &[u8] = {bytes};\n\n",
            idx = idx,
            key = key,
            bytes = fmt_slice(&sealed),
        ));
    }

    body.push_str("pub const SLOTS: &[&[u8]] = &[\n");
    for idx in 0..SLOT_ORDER.len() {
        body.push_str(&format!("    SLOT_{idx},\n"));
    }
    body.push_str("];\n");

    let out = manifest.join("src").join("sealed_data.rs");
    fs::write(&out, body).expect("write src/sealed_data.rs");
}
